spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
# logging
logging:
  level:
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}| [%thread] UserName=%X{UserId}, RequestId=%X{RequestId}| ServiceName=${spring.zipkin.service.name:${spring.application.name:}}, TraceId=%X{traceId:-}, SpanId=%X{spanId:-}|%-5level|[%class{36}.%M] %L: %msg %replace(%xException){'\r\n','~~'}%nopex%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}, [%thread] UserName=%X{UserId}, RequestId=%X{RequestId}| ServiceName=${spring.zipkin.service.name:${spring.application.name:}}, TraceId=%X{traceId:-}, SpanId=%X{spanId:-}|%-5level|[%class{36}.%M] %L: %msg %replace(%xException){'\r\n','~~'}%nopex%n"
