spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
logging:
  level:
    org.springframework.jdbc: TRACE